movie-platform/movie_app/urls.py
from django.urls import path,include
from .import views
app_name='movie_app'

urlpatterns=[
    path('',views.movie,name='movie'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movie-platform/movie_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from movie_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie_app.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie-platform/movie_app/models.py
from django.db import models
class Movie(models.Model):
    name=models.CharField(max_length=250)
    decscription=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to="images")

    def __str__(self):
        return self .name


# Create your models here.

movie-platform/movie_app/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=('name','decscription','year','image')
        # widgets={
        #     'name':forms.TextInput(attrs={'class':'form-control'}),
        #     'decscription': forms.Textarea(attrs={'class': 'form-control'}),
        #     'year': forms.TextInput(attrs={'type':'number'}),
        #     'image': forms.TextInput(attrs={'type':'file'}),
        # }


movie-platform/movie_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm
def movie(request):
    obj=Movie.objects.all()
    return render(request,'index.html',{'display':obj})

# def detail(request,movie_id):
#     return HttpResponse("This is movie no %s" %movie_id)


def detail(request, movie_id):
    movies = Movie.objects.get(id=movie_id)
    return render(request, 'detail.html', {'movie': movies})





def add_movie(request):
    if request.method == 'POST':
        name=request.POST.get('name')
        decsc = request.POST.get('decscription',)
        year = request.POST.get('year',)
        img = request.FILES['file']
        movie=Movie(name=name,decscription=decsc,year=year,image=img)
        movie.save()
        print("saved succesfully")
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():

        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method == 'POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')
# Create your views here.

movie-platform/templates/add.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<div class="well" style="background-color:#FFE4E1;width:100%;height:70px">
    <h2 class="h2">Adding Movies</h2>
</div>
<div class="container-fluid" >
	<div class="row">
			<div class="col-md-6">
						<form class="form-center" method="POST"  enctype="multipart/form-data">
	{% csrf_token %}
<!--	<h1>ADD PAGE</h1>-->
	<div>
		<label style="margin:20px">Name</label>
		<input type="text" name="name" placeholder="Enter your name" required style="visibility: visible;"><br>
	</div>

    <div>
		<label  >Description</label>
		<textarea name="decscription" rows="4" cols="50"></textarea>
	</div>
    <div>
		<label style="margin:24px">Year</label>
		<input type="number" name="year" placeholder="Enter your year" required><br>
	</div>
    <div>
		<label>File Upload</label>
		<input type="file" name="file"  required><br>
	</div>
    <div>
	<input type="submit">
	</div>
</form>
			</div>
		<div class="col-md-6" >

		</div>
	</div>
</div>
{% endblock %}

movie-platform/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie</title>
     <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style1.css' %}">
</head>
<body style="background-color:#F8F8FF">
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Platform
  </a>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

movie-platform/templates/delete.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    Are you want to delete?
  <input type="submit" value="delete" class="btn btn-primary">
</form>

movie-platform/templates/detail.html
{% extends 'base.html' %}
    {% block body %}

    <div class="container" style="margin-top:15px">

        <div class="row">

            <div class="col-md-6">

                <img src="{{movie.image.url}}" width="350"><br><br>

            </div>

            <div class="col-md-6">

                  <h1>{{movie.name}}</h1><br>
                  <h4 style="text-align:justify">{{movie.decscription}}</h4><br>
                    <h4>{{movie.year}}</h4><br>

                <a class="btn btn-primary" href="{% url 'movie_app:update' movie.id %}">update</a>
                <a class="btn btn-danger" href="{% url 'movie_app:delete' movie.id %}">Delete</a><br>

            </div>

        </div>


    </div>

    {% endblock %}

movie-platform/templates/detail1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>{{obj2.p_name}}<br>
    {{obj2.p_decscription}}<br>
    {{obj2.s_name}}<br></h2>
</body>
</html>

movie-platform/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    <table border="1">
        {{form}}
    </table>
  <input type="submit" value="update" class="btn btn-primary">
</form>

movie-platform/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="well" style="background-color:#FFE4E1;width:100%;height:70px">
    <a href="{% url 'movie_app:add_movie' %}" class="btn btn-info" id="button">ADD_MOVIE</a>
</div>
<div class="container" style="margin-top:18px">
    <div class="row">
        {% for i in display %}
        <div class="col-sm-3">
            <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{i.image.url}}" alt="Card image cap" width="100" height="300" style="padding:3px">
            <div class="card-body">
                 <h5 class="card-title">{{i.name}}</h5>
<!--                 <p class="card-text">{{i.decscription}}</p>-->
                 <a href="{% url 'movie_app:detail' i.id %}" class="btn btn-primary">Detail -></a>
            </div>
            </div>
        </div>
         {% endfor %}
    </div>
</div>
{% endblock %}

movie-platform/templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for j in obj1 %}
<!--<h2>{{j.p_name}}-->
<!--    {{j.p_decscription}}-->
<!--    {{j.s_name}}<br></h2>-->
<a href="{% url 'movie_app:plants' j.id %}">{{j.p_name}}</a><br>
{% endfor %}
</body>
</html>